groups:
  enable: []
logging:
  disable_existing_loggers: false
  formatters:
    error:
      format: '%(asctime)s %(name)s %(levelname)s %(filename)s::%(funcName)s[%(lineno)d]:%(message)s'
    simple:
      datefmt: '%Y-%m-%d %H:%M:%S'
      format: '%(asctime)s %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: simple
      level: INFO
      stream: ext://sys.stdout
    error_file_handler:
      backupCount: 20
      class: logging.handlers.RotatingFileHandler
      encoding: utf8
      filename: wx_error.log
      formatter: error
      level: ERROR
      maxBytes: 10485760
    info_file_handler:
      backupCount: 20
      class: logging.handlers.RotatingFileHandler
      encoding: utf8
      filename: wx_info.log
      formatter: simple
      level: INFO
      maxBytes: 10485760
  root:
    handlers:
    - console
    - info_file_handler
    - error_file_handler
    level: INFO
  version: 1
